@startuml
'Системы
actor "Админ" as User
participant "UI[Colab]\n(Браузер)" as UI
participant "Tg.Auth" as Auth

participant "Repo\n(GitHub)" as Repo
database "БД[Colab]\n(SQLite)" as DB

participant "Tg.Service" as Service


'Действия
User -> UI: Авторизация (GC)
UI --> User: OK

User -> UI: Настройки
UI -> UI: Установки
UI --> User: OK
User -> UI: Ввод (клиенты)
UI --> User: OK

User -> UI: Запуск
UI -> Auth: 2FA
Auth --> User: Коды
User -> UI: Авторизация (Tg)
UI -> Auth: Коды
UI <-- Auth: OK
UI --> User: OK

UI -> Repo: Импорт проекта
UI <-- Repo: Проект

UI -> DB: Connect
UI <-- DB: OK

UI -> DB: /GET users_blocked
UI <-- DB: users_blocked
UI --> User: OK

User -> UI: Сбор+Инвайты
UI -> Service: Сбор
UI <-- Service: OK
UI -> Service: Инвайты
UI <-- Service: OK
UI <-- Service: неOK - users_blocked

UI -> DB: /POST users_blocked
UI <-- DB: OK

UI -> Repo: Экспорт проекта
UI <-- Repo: OK

@enduml